image: Visual Studio 2017
platform:
  - x64
configuration:
  - Debug
before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\Tools\vsdevcmd.bat"
build:
  project: PathCopyCopy.sln
test: off
