image: Visual Studio 2015
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release
build:
  project: PathCopyCopy.sln
test: off
