image: Visual Studio 2019
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
platform:
  - Win32
  - x64
configuration:
  - Debug
  - Release
build:
  project: PathCopyCopy.sln
test: off
